package com.brainstation23.topandroidrepositories.ui.test_dialog.interactor

import com.brainstation23.topandroidrepositories.ui.base.interactor.MVPInteractor

interface TestDialogMVPInteractor : MVPInteractor