package com.brainstation23.topandroidrepositories.ui.test_fragment.interactor

import com.brainstation23.topandroidrepositories.ui.base.interactor.MVPInteractor

interface TestFragmentMVPInteractor : MVPInteractor